branch-defaults:
  main:
    environment: flask-continuous-delivery-env
global:
  application_name: flask-continuous-delivery
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
